apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-debt-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-debt-tracker
  template:
    metadata:
      labels:
        app: technical-debt-tracker
    spec:
      containers:
       - name: technical-debt-tracker
    image: technical-debt-tracker:latest  
    imagePullPolicy: Never                 
    ports:
      - containerPort: 8080